///scr_getT2()
return choose(//Dunpield
              spr_dunpieSif,
              //iFlynn
              spr_iflynnFEELS,
              spr_iflynnGASM,
              spr_iflynnHI,
              spr_iflynnLOVE,
              spr_iflynnLUCK,
              spr_iflynnLUL,
              spr_iflynnLURK,
              //LadyZoe
              spr_ladyz0Yes,
              //leijonaervasti
              spr_leijonPango,
              //N3BoySha
              spr_n3boysHorns,
              //sasoriox
              spr_sasori2Kappaccino,
              //SwissCheesy_ez
              spr_swisscVoltLUL,
              //Tygastripe
              spr_tygastHEY);
