///scr_tier2()
global.T2 = ds_list_create();
ds_list_add(global.T2,
    //Dunpield
    spr_dunpieSif,
    //iFlynn
    spr_iflynnFEELS,
    spr_iflynnGASM,
    spr_iflynnHI,
    spr_iflynnLOVE,
    spr_iflynnLUCK,
    spr_iflynnLUL,
    spr_iflynnLURK,
    //LadyZoe
    spr_ladyz0Yes,
    //leijonaervasti
    spr_leijonPango,
    //N3BoySha
    spr_n3boysHorns,
    //sasoriox
    spr_sasori2Kappaccino,
    //Shul
    spr_shulCry,
    spr_shulDab,
    spr_shulHey,
    spr_shulLewd,
    spr_shulLove,
    spr_shulLUL,
    spr_shulLurk,
    spr_shulRage,
    spr_shulS,
    spr_shulSalt,
    spr_shulThink,
    spr_shulUp,
    //SwissCheesy_ez
    spr_swisscVoltLUL,
    //Tygastripe
    spr_tygastHEY);
